routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\{
    CategoryController,
    NewsletterController,
    OfferController,
    ProductController,
    ReviewController
};
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
		Route::get('icons', ['as' => 'pages.icons', 'uses' => 'App\Http\Controllers\PageController@icons']);
		Route::get('maps', ['as' => 'pages.maps', 'uses' => 'App\Http\Controllers\PageController@maps']);
		Route::get('notifications', ['as' => 'pages.notifications', 'uses' => 'App\Http\Controllers\PageController@notifications']);
		Route::get('rtl', ['as' => 'pages.rtl', 'uses' => 'App\Http\Controllers\PageController@rtl']);
		Route::get('tables', ['as' => 'pages.tables', 'uses' => 'App\Http\Controllers\PageController@tables']);
		Route::get('typography', ['as' => 'pages.typography', 'uses' => 'App\Http\Controllers\PageController@typography']);
		Route::get('upgrade', ['as' => 'pages.upgrade', 'uses' => 'App\Http\Controllers\PageController@upgrade']);
    });

    Route::group(['middleware' => 'auth'], function () {
        Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
        Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
        Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
        Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    });

    Route::group(['middleware' => 'auth', 'prefix' => '/admin', 'as' => 'admin.'], function () {
        Route::resource('categories', CategoryController::class);
        Route::resource('products', ProductController::class);
        Route::resource('offers', OfferController::class);
        Route::resource('reviews', ReviewController::class);
        Route::get('/products/{product}/reviews',[ReviewController::class,'productReviews'])->name('productReviews');
        Route::get('{newsletter}/mail',[NewsletterController::class,'mail'])->name('mail');
        Route::resource('newsletters', NewsletterController::class);
});

app/Models/Offer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\Translatable\HasTranslations;

class Offer extends Model implements HasMedia
{
    use HasFactory, HasTranslations, InteractsWithMedia;
    public $translatable = ['name'];
    protected $fillable = [
        'name',
        'type',
        'discount',
        'started_at',
        'ended_at',
        'product_id',
        'category_id',
    ];

    public function products()
    {
        return $this->belongsToMany(Product::class,'product_offer','offer_id','product_id');
    }
    public function categories()
    {
        return $this->belongsToMany(Category::class,'category_offer','offer_id','category_id');
    }
}

app/Http/Controllers/Admin/OfferController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Offer;
use App\Models\Product;
use Illuminate\Http\Request;

class OfferController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $offers = Offer::latest();
        if ($request->filled('search')) {
            $offers->where('name', 'like', "%$request->search%");
            $offers->orWhere('type', 'like', "%$request->search%");
            $offers->orWhere('discount', 'like', "%$request->search%");
            $offers->orWhere('started_at', 'like', "%$request->search%");
            $offers->orWhere('ended_at', 'like', "%$request->search%");
        }
        if ($request->filled('type')) {
            $offers->whereIn('type', $request->type);
        }

        if ($request->filled('sort')) {
            if ($request->filled('order')) {
                if ($request->order == 'ascending') {
                    if ($request->sort == 'name_ar') {
                        $offers = Offer::orderBy('name', 'asc');
                    }
                    if ($request->sort == 'name_en') {
                        $offers = Offer::orderBy('name', 'asc');
                    }
                    if ($request->sort == 'start_date') {
                        $offers = Offer::orderBy('started_at', 'asc');
                    }
                    if ($request->sort == 'end_date') {
                        $offers = Offer::orderBy('ended_at', 'asc');
                    }
                    if ($request->sort == 'creation_date') {
                        $offers = Offer::orderBy('created_at', 'asc');
                    }
                }
                if ($request->order == 'descending') {
                    if ($request->sort == 'name_ar') {
                        $offers = Offer::orderBy('name->ar', 'desc');
                    }
                    if ($request->sort == 'name_en') {
                        $offers = Offer::orderBy('name', 'desc');
                    }
                    if ($request->sort == 'start_date') {
                        $offers = Offer::orderBy('started_at', 'desc');
                    }
                    if ($request->sort == 'end_date') {
                        $offers = Offer::orderBy('ended_at', 'desc');
                    }
                    if ($request->sort == 'creation_date') {
                        $offers = Offer::orderBy('created_at', 'desc');
                    }
                }
            }
                else {
                    if ($request->sort == 'name_ar') {
                        $offers = Offer::orderBy('name->ar', 'asc');
                    }
                    if ($request->sort == 'name_en') {
                        $offers = Offer::orderBy('name', 'asc');
                    }
                    if ($request->sort == 'start_date') {
                        $offers = Offer::orderBy('started_at', 'asc');
                    }
                    if ($request->sort == 'end_date') {
                        $offers = Offer::orderBy('ended_at', 'asc');
                    }
                    if ($request->sort == 'creation_date') {
                        $offers = Offer::orderBy('created_at', 'asc');
                    }
                }
        }

        $offers = $offers->paginate(10);

        return view('admin.offers.index',['offers'=> $offers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::all();
        $categories = Category::all();
        return view('admin.offers.create',['categories' => $categories, 'products' => $products]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = $request->validate([
            'name'          => 'required',
            'name.*'        => 'required|min:3',
            'discount'      =>  'required|numeric',
            'type'          =>  'required',
            'started_at'    => 'required|date|before:ended_at',
            'ended_at'      => 'required|date|after:started_at',
            'products'      => 'array',
            'products.*'    => 'numeric|exists:products,id',
            'categories'    => 'array',
            'categories.*'  => 'numeric|exists:categories,id',
        ]);

        $offer = Offer::create($validation);
        $offer->products()->attach($request->products);
        $offer->categories()->attach($request->categories);
        $categories = $offer->categories;
        if ($categories) {
            foreach ($categories as $category) {
                foreach ($category->products as $product) {
                    if ($product->offers->contains($offer->id)) {
                        continue;
                    }
                    else {
                        $offer->products()->attach($product->id);
                    }
                }
            }
        }

        return redirect()->route('admin.offers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function show(Offer $offer)
    {
        return view('admin.offers.show',['offer'=>$offer]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function edit(Offer $offer)
    {
        $products = Product::all();
        $categories = Category::all();
        return view('admin.offers.edit',['offer'=>$offer, 'categories' => $categories, 'products' => $products]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Offer $offer)
    {
        $validation = $request->validate([
            'name'         => 'required',
            'name.*'       => 'required|min:3',
            'discount'     =>  'required|numeric',
            'type'         =>  'required',
            'started_at'   => 'required|date|before:ended_at',
            'ended_at'     => 'required|date|after:started_at',
            'products'     => 'array',
            'products.*'   => 'numeric|exists:products,id',
            'categories'   => 'array',
            'categories.*' => 'numeric|exists:categories,id',
        ]);

        foreach ($validation['name'] as $lang => $name) {
            $offer->setTranslation('name', $lang, $name);
        }
        $offer->discount   =  $validation['discount'];
        $offer->type       =  $validation['type'];
        $offer->started_at = $validation['started_at'];
        $offer->ended_at   = $validation['ended_at'];
        if ($request->filled('products')) {
            $offer->products()->detach();
            $offer->products()->attach($request->products);
        }
        if ($request->filled('categories')) {
            $offer->categories()->detach();
            $offer->categories()->attach($request->categories);
        }
        $categories = $offer->categories;
        if ($categories) {
            foreach ($categories as $category) {
                foreach ($category->products as $product) {
                    if ($product->offers->contains($offer->id)) {
                        continue;
                    }
                    else {
                        $offer->products()->attach($product->id);
                    }
                }
            }
        }
        $offer->save();

        return redirect()->route('admin.offers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Offer $offer)
    {
        $offer->products()->detach();
        $offer->categories()->detach();
        $offer->delete();
        return redirect()->route('admin.offers.index');
    }
}

resources/views/Admin/offers/create.blade.php
@extends('layouts.app', ['page' => __('New Offer'), 'pageSlug' => 'offers'])

@section('content')
    <div class="row">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">{{ __('Create Offer') }}</h5>
                </div>
                <form method="post" action="{{ route('admin.offers.store') }}" autocomplete="off"
                    enctype="multipart/form-data">
                    <div class="card-body">
                        @csrf

                        @include('alerts.success')

                        <div class="form-group{{ $errors->has("name['en']") ? ' has-danger' : '' }}">
                            <label>{{ __('English Name') }}</label>
                            <input type="text" name="name[en]" id="input-name_en"
                                class="form-control{{ $errors->has("name['en']") ? ' is-invalid' : '' }}"
                                placeholder="{{ __('English Name') }}" value="{{ old("name['en']") }}" required="true"
                                aria-required="true">
                            @include('alerts.feedback', ['field' => "name['en']"])
                        </div>
                        <div class="form-group{{ $errors->has("name['ar']") ? ' has-danger' : '' }}">
                            <label>{{ __('Arabic Name') }}</label>
                            <input type="text" name="name[ar]" id="input-name_ar"
                                class="form-control{{ $errors->has("name['ar']") ? ' is-invalid' : '' }}"
                                placeholder="{{ __('Arabic Name') }}" value="{{ old("name['ar']") }}" required="true"
                                aria-required="true">
                            @include('alerts.feedback', ['field' => "name['ar']"])
                        </div>

                        <div class="form-group{{ $errors->has('discount') ? ' has-danger' : '' }}">
                            <label>{{ __('Discount') }}</label>
                            <input type="text" name="discount" id="input-discount"
                                class="form-control{{ $errors->has('discount') ? ' is-invalid' : '' }}"
                                placeholder="{{ __('Discount') }}" value="{{ old('discount') }}" required="true"
                                aria-required="true">
                            @include('alerts.feedback', ['field' => 'discount'])
                        </div>

                        <div class="form-group{{ $errors->has('type') ? ' has-danger' : '' }}">
                            <label>{{ __('Type of discount') }}</label>
                            <div class="form-check form-check-radio">
                                <label class="form-check-label">
                                    <input class="form-check-input{{ $errors->has('type') ? ' is-invalid' : '' }}"
                                        type="radio" name="type" id="input-type" value="Constant"
                                        {{ 'Constant' == request()->query('type') ? 'checked' : '' }}>
                                    Constant
                                    <span class="form-check-sign"></span>
                                </label>
                            </div>
                            <div class="form-check form-check-radio">
                                <label class="form-check-label">
                                    <input class="form-check-input{{ $errors->has('type') ? ' is-invalid' : '' }}"
                                        type="radio" name="type" id="input-type" value="Percentage"
                                        {{ 'Percentage' == request()->query('type') ? 'checked' : '' }}>
                                    Percentage
                                    <span class="form-check-sign"></span>
                                </label>
                            </div>
                            @include('alerts.feedback', ['field' => 'type'])
                        </div>

                        <div class="form-group{{ $errors->has('started_at') ? ' has-danger' : '' }}">
                            <label>{{ __('Start Date') }}</label>
                            <input type="date" name="started_at" id="input-started_at"
                                class="form-control{{ $errors->has('started_at') ? ' is-invalid' : '' }}"
                                placeholder="{{ __('Start Date') }}" value="{{ old('started_at') }}" required="true"
                                aria-required="true">
                            @include('alerts.feedback', ['field' => 'started_at'])
                        </div>
                        <div class="form-group{{ $errors->has('ended_at') ? ' has-danger' : '' }}">
                            <label>{{ __('End Date') }}</label>
                            <input type="date" name="ended_at" id="input-ended_at"
                                class="form-control{{ $errors->has('ended_at') ? ' is-invalid' : '' }}"
                                placeholder="{{ __('End Date') }}" value="{{ old('ended_at') }}" required="true"
                                aria-required="true">
                            @include('alerts.feedback', ['field' => 'ended_at'])
                        </div>

                        <div class="form-group{{ $errors->has('categories') ? ' has-danger' : '' }}">
                            <label>{{ __('Categories') }} <small>(Fill if you want to apply offer on
                                    categories)</small></label>
                            <select multiple class="form-control{{ $errors->has('categories') ? ' is-invalid' : '' }}"
                                name="categories[]" id="input-categories" value="{{ old('categories[]') }}">
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">
                                        {{ $category->name }}/{{ $category->getTranslation('name', 'ar') }}
                                    </option>
                                @endforeach
                            </select>
                            @include('alerts.feedback', ['field' => 'categories'])
                        </div>

                        <div class="form-group{{ $errors->has('products') ? ' has-danger' : '' }}">
                            <label>{{ __('Products') }} <small>(Fill if you want to apply offer on
                                    products)</small></label>
                            <select multiple class="form-control{{ $errors->has('products') ? ' is-invalid' : '' }}"
                                name="products[]" id="input-products" value="{{ old('products[]') }}">
                                @foreach ($products as $product)
                                    <option value="{{ $product->id }}">
                                        {{ $product->name }}/{{ $product->getTranslation('name', 'ar') }}
                                    </option>
                                @endforeach
                            </select>
                            <small>You can fill both categories and products</small>
                            @include('alerts.feedback', ['field' => 'products'])
                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-fill btn-primary">{{ __('Save') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/offers/edit.blade.php
@extends('layouts.app', ['page' => __('Edit Offer'), 'pageSlug' => 'offers'])

@section('content')
    <div class="row">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">{{ __('Create Offer') }}</h5>
                </div>
                <form method="post" action="{{ route('admin.offers.update', $offer) }}" autocomplete="off"
                    enctype="multipart/form-data">
                    <div class="card-body">
                        @csrf
                        @method('PUT')

                        @include('alerts.success')

                        <div class="form-group{{ $errors->has("name['en']") ? ' has-danger' : '' }}">
                            <label>{{ __('English Name') }}</label>
                            <input type="text" name="name[en]" id="input-name_en"
                                class="form-control{{ $errors->has("name['en']") ? ' is-invalid' : '' }}"
                                placeholder="{{ __('English Name') }}"
                                value="{{ $offer->getTranslation('name', 'en') }}" required="true" aria-required="true">
                            @include('alerts.feedback', ['field' => "name['en']"])
                        </div>
                        <div class="form-group{{ $errors->has("name['ar']") ? ' has-danger' : '' }}">
                            <label>{{ __('Arabic Name') }}</label>
                            <input type="text" name="name[ar]" id="input-name_ar"
                                class="form-control{{ $errors->has("name['ar']") ? ' is-invalid' : '' }}"
                                placeholder="{{ __('Arabic Name') }}"
                                value="{{ $offer->getTranslation('name', 'ar') }}" required="true" aria-required="true">
                            @include('alerts.feedback', ['field' => "name['ar']"])
                        </div>

                        <div class="form-group{{ $errors->has('discount') ? ' has-danger' : '' }}">
                            <label>{{ __('Discount') }}</label>
                            <input type="text" name="discount" id="input-discount"
                                class="form-control{{ $errors->has('discount') ? ' is-invalid' : '' }}"
                                placeholder="{{ __('Discount') }}" value="{{ $offer->discount }}" required="true"
                                aria-required="true">
                            @include('alerts.feedback', ['field' => 'discount'])
                        </div>

                        <div class="form-group{{ $errors->has('type') ? ' has-danger' : '' }}">
                            <label>{{ __('Type of discount') }}</label>
                            <div class="form-check form-check-radio">
                                <label class="form-check-label">
                                    <input class="form-check-input{{ $errors->has('type') ? ' is-invalid' : '' }}"
                                        type="radio" name="type" id="input-type" value="Constant"
                                        {{ 'Constant' == $offer->type ? 'checked' : '' }}>
                                    Constant
                                    <span class="form-check-sign"></span>
                                </label>
                            </div>
                            <div class="form-check form-check-radio">
                                <label class="form-check-label">
                                    <input class="form-check-input{{ $errors->has('type') ? ' is-invalid' : '' }}"
                                        type="radio" name="type" id="input-type" value="Percentage"
                                        {{ 'Percentage' == $offer->type ? 'checked' : '' }}>
                                    Percentage
                                    <span class="form-check-sign"></span>
                                </label>
                            </div>
                            @include('alerts.feedback', ['field' => 'type'])
                        </div>

                        <div class="form-group{{ $errors->has('started_at') ? ' has-danger' : '' }}">
                            <label>{{ __('Start Date') }}</label>
                            <input type="date" name="started_at" id="input-started_at"
                                class="form-control{{ $errors->has('started_at') ? ' is-invalid' : '' }}"
                                placeholder="{{ __('Start Date') }}" value="{{ $offer->started_at }}" required="true"
                                aria-required="true">
                            @include('alerts.feedback', ['field' => 'started_at'])
                        </div>
                        <div class="form-group{{ $errors->has('ended_at') ? ' has-danger' : '' }}">
                            <label>{{ __('End Date') }}</label>
                            <input type="date" name="ended_at" id="input-ended_at"
                                class="form-control{{ $errors->has('ended_at') ? ' is-invalid' : '' }}"
                                placeholder="{{ __('End Date') }}" value="{{ $offer->ended_at }}" required="true"
                                aria-required="true">
                            @include('alerts.feedback', ['field' => 'ended_at'])
                        </div>

                        <div class="form-group{{ $errors->has('categories') ? ' has-danger' : '' }}">
                            <label>{{ __('Categories') }} <small>(Fill if you want to apply offer on
                                    categories)</small></label>
                            <select multiple class="form-control{{ $errors->has('categories') ? ' is-invalid' : '' }}"
                                name="categories[]" id="input-categories" value="{{ $offer->category_id }} ">
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}"
                                        {{ $category->offers->contains($category->id) ? 'selected' : '' }}>
                                        {{ $category->name }}/{{ $category->getTranslation('name', 'ar') }}
                                    </option>
                                @endforeach
                            </select>
                            @include('alerts.feedback', ['field' => 'categories'])
                        </div>

                        <div class="form-group{{ $errors->has('products') ? ' has-danger' : '' }}">
                            <label>{{ __('Products') }} <small>(Fill if you want to apply offer on
                                    products)</small></label>
                            <select multiple class="form-control{{ $errors->has('products') ? ' is-invalid' : '' }}"
                                name="products[]" id="input-products" value="{{ $offer->product_id }}">
                                @foreach ($products as $product)
                                    <option value="{{ $product->id }}"
                                        {{ $product->offers->contains($product->id) ? 'selected' : '' }}>
                                        {{ $product->name }}/{{ $product->getTranslation('name', 'ar') }}
                                    </option>
                                @endforeach
                            </select>
                            <small>You can fill both categories and products</small>
                            @include('alerts.feedback', ['field' => 'products'])
                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-fill btn-primary">{{ __('Save') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/offers/show.blade.php
@extends('layouts.app', ['page' => __('offers'), 'pageSlug' => 'offers'])

@section('content')
    <div class="row">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header mb-5">
                    <h3 class="card-title">Offer Info</h3>
                </div>
                <div class="card-body">
                    <div class="typography-line">
                        <span>English name</span>
                        <p class="text-primary">
                            {{ $offer->getTranslation('name', 'en') }}</p>
                    </div>
                    <div class="typography-line">
                        <span>Arabic name</span>
                        <p class="text-primary">
                            {{ $offer->getTranslation('name', 'ar') }}</p>
                    </div>
                    <div class="typography-line">
                        <span>Discount</span>
                        <p class="text-primary">
                            {{ $offer->discount }}</p>
                    </div>
                    <div class="typography-line">
                        <span>Type of discount</span>
                        <p class="text-primary">
                            {{ $offer->type }}</p>
                    </div>
                    <div class="typography-line">
                        <span>Start Date</span>
                        <p class="text-primary">
                            {{ $offer->started_at }}</p>
                    </div>
                    <div class="typography-line">
                        <span>End Date</span>
                        <p class="text-primary">
                            {{ $offer->ended_at }}</p>
                    </div>
                    <div class="typography-line">
                        <span>Created at</span>
                        <p class="text-primary">
                            {{ $offer->created_at }}</p>
                    </div>
                    <div class="row">
                        <div class="col-1 text-left">
                            <a href="{{ route('admin.offers.edit', $offer) }}" class="btn btn-sm btn-primary"> Edit </a>
                        </div>
                        <div class="col-1.5 text-left">
                            <form action="{{ route('admin.offers.destroy', $offer) }}" method="post">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-sm btn-primary" data-original-title="" title="">
                                    {{ __('Delete') }}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection