routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\{
    CategoryController,
    NewsletterController,
    OfferController,
    ProductController,
    ReviewController
};
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
		Route::get('icons', ['as' => 'pages.icons', 'uses' => 'App\Http\Controllers\PageController@icons']);
		Route::get('maps', ['as' => 'pages.maps', 'uses' => 'App\Http\Controllers\PageController@maps']);
		Route::get('notifications', ['as' => 'pages.notifications', 'uses' => 'App\Http\Controllers\PageController@notifications']);
		Route::get('rtl', ['as' => 'pages.rtl', 'uses' => 'App\Http\Controllers\PageController@rtl']);
		Route::get('tables', ['as' => 'pages.tables', 'uses' => 'App\Http\Controllers\PageController@tables']);
		Route::get('typography', ['as' => 'pages.typography', 'uses' => 'App\Http\Controllers\PageController@typography']);
		Route::get('upgrade', ['as' => 'pages.upgrade', 'uses' => 'App\Http\Controllers\PageController@upgrade']);
    });

    Route::group(['middleware' => 'auth'], function () {
        Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
        Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
        Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
        Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
    });

    Route::group(['middleware' => 'auth', 'prefix' => '/admin', 'as' => 'admin.'], function () {
        Route::resource('categories', CategoryController::class);
        Route::resource('products', ProductController::class);
        Route::resource('offers', OfferController::class);
        Route::resource('reviews', ReviewController::class);
        Route::get('/products/{product}/reviews',[ReviewController::class,'productReviews'])->name('productReviews');
        Route::get('{newsletter}/mail',[NewsletterController::class,'mail'])->name('mail');
        Route::resource('newsletters', NewsletterController::class);
});

app/Models/Newsletter.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\Translatable\HasTranslations;

class Newsletter extends Model implements HasMedia
{
    use HasFactory, HasTranslations, InteractsWithMedia;
    public $translatable = ['title', 'content'];
    protected $fillable  = ['title', 'content'];
}

app/Http/Controllers/Admin/NewsletterController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Mail\NewsletterMail;
use App\Models\Newsletter;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class NewsletterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $newsletters = Newsletter::latest();

        if ($request->filled('search')) {
            $newsletters->where('title', 'like', "%$request->search%");
            $newsletters->orWhere('content', 'like', "%$request->search%");
        }

        $newsletters  = $newsletters->paginate(10);
        return view('admin.newsletters.index', ['newsletters' => $newsletters]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.newsletters.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = $request->validate([
            'title'     => 'required',
            'title.*'   => 'required|min:3',
            'content'     => 'required',
            'content.*'   => 'required|string',
            'images'   => 'required|array',
            'images.*' => 'required|file|image',
        ]);
        $newsletter = Newsletter::create($validation);
        if ($request->hasFile('images')) {
            $fileAdders = $newsletter->addMultipleMediaFromRequest(['images'])
            ->each(function ($fileAdder) {
                $fileAdder->preservingOriginal()->toMediaCollection('images');
            });
        }
        $subscribers = User::all();
        $subscribers = $subscribers->where('subscribed',1);
        foreach ($subscribers as $subscriber) {
            Mail::to($subscriber->email)->send(new NewsletterMail($subscriber->name, $newsletter));
        }
        return redirect()->route('admin.newsletters.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Newsletter  $newsletter
     * @return \Illuminate\Http\Response
     */
    public function show(Newsletter $newsletter)
    {
        $mediaItems = $newsletter->getMedia('images');
        return view('admin.newsletters.show', ['newsletter' => $newsletter, 'mediaItems' => $mediaItems]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Newsletter  $newsletter
     * @return \Illuminate\Http\Response
     */
    public function edit(Newsletter $newsletter)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Newsletter  $newsletter
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Newsletter $newsletter)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Newsletter  $newsletter
     * @return \Illuminate\Http\Response
     */
    public function destroy(Newsletter $newsletter)
    {
        $newsletter->clearMediaCollection('images');
        $newsletter->delete();
        return redirect()->route('admin.newsletters.index');
    }

    public function mail($newsletter_id)
    {
        $newsletter = Newsletter::findOrFail($newsletter_id);
        $subscribers = User::all();
        $subscribers = $subscribers->where('subscribed',1);
        foreach ($subscribers as $subscriber) {
            Mail::to($subscriber->email)->send(new NewsletterMail($subscriber->name, $newsletter));
        }
        return redirect()->route('admin.newsletters.index');
    }
}

resources/views/Admin/newsletters/create.blade.php
@extends('layouts.app', ['page' => __('New newsletter'), 'pageSlug' => 'newsletters'])

@section('content')
    <div class="row">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">{{ __('Create newsletter') }}</h5>
                </div>
                <form method="post" action="{{ route('admin.newsletters.store') }}" autocomplete="off"
                    enctype="multipart/form-data">
                    <div class="card-body">
                        @csrf

                        @include('alerts.success')

                        <div class="form-group{{ $errors->has("title['en']") ? ' has-danger' : '' }}">
                            <label>{{ __('English title') }}</label>
                            <input type="text" name="title[en]" id="input-title_en"
                                class="form-control{{ $errors->has("title['en']") ? ' is-invalid' : '' }}"
                                placeholder="{{ __('English title') }}" value="{{ old("title['en']") }}" required="true"
                                aria-required="true">
                            @include('alerts.feedback', ['field' => "title['en']"])
                        </div>

                        <div class="form-group{{ $errors->has("title['ar']") ? ' has-danger' : '' }}">
                            <label>{{ __('Arabic title') }}</label>
                            <input type="text" name="title[ar]" id="input-title_ar"
                                class="form-control{{ $errors->has("title['ar']") ? ' is-invalid' : '' }}"
                                placeholder="{{ __('Arabic title') }}" value="{{ old("title['ar']") }}"
                                required="true" aria-required="true">
                            @include('alerts.feedback', ['field' => "title['ar']"])
                        </div>

                        <div class="form-group{{ $errors->has("content['en']") ? ' has-danger' : '' }}">
                            <label>{{ __('English content') }}</label>
                            <textarea type="text" name="content[en]" id="input-content_en"
                                class="form-control{{ $errors->has("content['en']") ? ' is-invalid' : '' }}"
                                value="{{ old("content['en']") }}" required="true" aria-required="true">
                            </textarea>
                            @include('alerts.feedback', ['field' => "content['en']"])
                        </div>

                        <div class="form-group{{ $errors->has("content['ar']") ? ' has-danger' : '' }}">
                            <label>{{ __('Arabic content') }}</label>
                            <textarea type="text" name="content[ar]" id="input-content_ar"
                                class="form-control{{ $errors->has("content['ar']") ? ' is-invalid' : '' }}"
                                value="{{ old("content['ar']") }}" required="true" aria-required="true">
                            </textarea>
                            @include('alerts.feedback', ['field' => "content['ar']"])
                        </div>

                        <label class=" col-form-label">{{ __('Images') }}</label>
                        <div class="custom-file {{ $errors->has('images') ? ' has-danger' : '' }}">
                            <input class="form-control file{{ $errors->has('images') ? ' is-invalid' : '' }}"
                                name="images[]" id="input-images" type="file" multiple="multiple"
                                placeholder="{{ __('Upload Images') }}" value="{{ old('images[]') }}" required="true"
                                aria-required="true" />
                            @include('alerts.feedback', ['field' => 'images'])
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-fill btn-primary">{{ __('Save') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/newsletters/index.blade.php
@extends('layouts.app', ['page' => __('newsletters'), 'pageSlug' => 'newsletters'])

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"> Here you can manage newsletters</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <form action="{{ route('admin.newsletters.index') }}">
                                <div class="field">
                                    <label class="label tim-icons icon-zoom-split">{{ __(' Search') }}</label>
                                    <div class="control is-expanded">
                                        <input class="input" type="text" placeholder="Search ..." name="search"
                                            value="{{ request()->query('search', '') }}">
                                    </div>
                                </div>
                        </div>
                        <div class="field col-md-12">
                            <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                            <button type="reset" class="btn btn-sm btn-primary">Reset</button>
                            <a href="{{ route('admin.newsletters.create') }}" class="btn btn-sm btn-primary">Add
                                newsletter </a>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card ">
                <div class="card-header">
                    <h4 class="card-title">Newsletters table</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table tablesorter " id="">
                            <thead class=" text-primary">
                                <tr>
                                    {{-- <th class="text-center">
                                        #
                                    </th> --}}
                                    <th>
                                        English title
                                    </th>
                                    <th>
                                        Arabic title
                                    </th>
                                    <th>
                                        Creation date
                                    </th>
                                    <th class="text-right">
                                        Actions
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($newsletters as $newsletter)
                                    <tr>
                                        <td>
                                            <a
                                                href="{{ route('admin.newsletters.show', $newsletter) }}">{{ $newsletter->title }}</a>
                                        </td>
                                        <td>
                                            <a
                                                href="{{ route('admin.newsletters.show', $newsletter) }}">{{ $newsletter->getTranslation('title', 'ar') }}</a>
                                        </td>
                                        <td>
                                            {{ $newsletter->created_at }}
                                        </td>
                                        <td class="td-actions text-right">
                                            <form action="{{ route('admin.newsletters.destroy', $newsletter) }}"
                                                method="post">
                                                @csrf
                                                @method('delete')
                                                <a rel="tooltip" class="btn btn-success btn-sm btn-round btn-icon"
                                                    href="{{ route('admin.mail', $newsletter->id) }}"
                                                    data-original-title="" title="">
                                                    <i class="tim-icons icon-send"></i>
                                                    <div class="ripple-container"></div>
                                                </a>
                                                <button type="submit" rel="tooltip"
                                                    class="btn btn-danger btn-sm btn-round btn-icon" data-original-title=""
                                                    title="">
                                                    <i class="tim-icons icon-simple-remove"></i>
                                                    <div class="ripple-container"></div>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-3 text-center m-auto">
                            {{ $newsletters->links('pagination::bootstrap-4') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/newsletters/show.blade.php
@extends('layouts.app', ['page' => __('newsletters'), 'pageSlug' => 'newsletters'])

@section('content')
    <div class="row">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header mb-5">
                    <h3 class="card-title">Newsletter Info</h3>
                </div>
                <div class="card-body">
                    <div class="typography-line">
                        <span>English title</span>
                        <p class="text-primary">
                            {{ $newsletter->getTranslation('title', 'en') }}</p>
                    </div>
                    <div class="typography-line">
                        <span>Arabic title</span>
                        <p class="text-primary">
                            {{ $newsletter->getTranslation('title', 'ar') }}</p>
                    </div>
                    <div class="typography-line">
                        <span>English content</span>
                        <p class="text-primary">
                            {{ $newsletter->getTranslation('content', 'en') }}</p>
                    </div>
                    <div class="typography-line">
                        <span>Arabic content</span>
                        <p class="text-primary">
                            {{ $newsletter->getTranslation('content', 'ar') }}</p>
                    </div>
                    <div class="typography-line">
                        <span>Created at</span>
                        <p class="text-primary">
                            {{ $newsletter->created_at }}</p>
                    </div>
                    <div class="row">
                        <div class="col-1 text-left">
                            <a href="{{ route('admin.mail', $newsletter->id) }}" class="btn btn-sm btn-primary"> Send
                            </a>
                        </div>
                        <div class="col-1.5 text-left">
                            <form action="{{ route('admin.newsletters.destroy', $newsletter) }}" method="post">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-sm btn-primary" data-original-title="" title="">
                                    {{ __('Delete') }}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        @foreach ($mediaItems as $mediaItem)
            <div class="col-md-5">
                <div class="card">
                    <div class="card-body">
                        <img class="card-img" src="{{ $mediaItem->getUrl() }}" alt="newsletter image">
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection